### ISSUE TITLE
Castle.Core fails to mock interfaces passing value types by reference

### ISSUE THREAD

**Issue by TAGC** [castleproject/Core#339]
(Cross-posting some details from nsubstitute/NSubstitute#378)

C# 7.2 introduced [the possibility of using reference semantics for value types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2#reference-semantics-with-value-types) - this is done by applying the `in` modifier for value-type parameters in method signatures.

Castle.Core does not seem to support generating mocks for interfaces that use `in` modifiers for value types. This has been reproduced using Castle.Core indirectly through the latest stable versions of Moq and NSubstitute:

```cs
namespace SomeProject.Tests
{
    public readonly struct Struct
    {
    }

    public interface IStructByRefConsumer
    {
        void Consume(in Struct message);
    }

    public interface IStructByValueConsumer
    {
        void Consume(Struct message);
    }

    public class TempSpec
    {
        // Fails.
        [Fact]
        internal void Struct_ByRef_Moq_Test()
        {
            _ = Mock.Of<IStructByRefConsumer>();
        }

        // Fails.
        [Fact]
        internal void Struct_ByRef_NSubstitute_Test()
        {
            _ = Substitute.For<IStructByRefConsumer>();
        }

        // Passes.
        [Fact]
        internal void Struct_ByValue_Moq_Test()
        {
            _ = Mock.Of<IStructByValueConsumer>();
        }

        // Passes.
        [Fact]
        internal void Struct_ByValue_NSubstitute_Test()
        {
            _ = Substitute.For<IStructByValueConsumer>();
        }
    }
}
```

Posted below is the part of the stracktrace that's common between the failing Moq and NSubstitute tests:

```
Result StackTrace:	
at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.CreateType(TypeBuilder type)
   at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType()
   at Castle.DynamicProxy.Generators.InterfaceProxyWithoutTargetGenerator.GenerateType(String typeName, Type proxyTargetType, Type[] interfaces, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.<>c__DisplayClass6_0.<GenerateCode>b__0(String n, INamingScope s)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, IInterceptor[] interceptors)
```

**Comment by TAGC** [comment]
For what it's worth, here's the generated IL for each interface:

```cs
.class interface public abstract auto ansi 
  SomeProject.Tests.IStructByRefConsumer
{

  .method public hidebysig virtual newslot abstract instance void 
    Consume(
      valuetype SomeProject.Tests.Struct& modreq ([System.Runtime.InteropServices]System.Runtime.InteropServices.InAttribute) message
    ) cil managed 
  {
    .param [1] 
    .custom instance void [System.Runtime]System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor() 
      = (01 00 00 00 )
    // Can't find a body
  } // end of method IStructByRefConsumer::Consume
} // end of class SomeProject.Tests.IStructByRefConsumer
```

```cs
.class interface public abstract auto ansi 
  SomeProject.Tests.IStructByValueConsumer
{

  .method public hidebysig virtual newslot abstract instance void 
    Consume(
      valuetype SomeProject.Tests.Struct message
    ) cil managed 
  {
    // Can't find a body
  } // end of method IStructByValueConsumer::Consume
} // end of class SomeProject.Tests.IStructByValueConsumer
```

**Comment by TAGC** [comment]
And also, the [source code](https://github.com/dotnet/coreclr/blob/57ee22e6086af5dfc06651dc002e24a71c3999ee/src/mscorlib/src/System/Reflection/Emit/TypeBuilder.cs#L2015) for the last line of that stacktrace.

**Comment by stakx** [comment]
FWIW, all of your tests pass just fine for me with the following NuGet package versions:

* Castle.Core 4.2.1
* Moq 4.8.0
* NSubstitute 3.1.0

However, there appears to be a regression in Moq 4.8.1 and 4.8.2 causing the Moq-based tests to fail in those versions. I will open an issue over at [moq/moq4](https://github.com/moq/moq4).

**Comment by TAGC** [comment]
Try .NET Core instead of .NET Framework. I've got a suspicion it might be a problem with corefx.

**Comment by stakx** [comment]
Yes, the tests fail when running under .NET Core.

I seem to remember that DynamicProxy might not emit custom modifiers for its .NET Standard target (see `FEATURE_EMIT_CUSTOMMODIFIERS` compilation symbol in `common.props`) simply because custom modifiers might not be supported under .NET Standard 1.3 (which is the one DynamicProxy targets, IIRC).

The new C# `in` keyword gets emitted as a custom modifier (modreq), so if DynamicProxy can't emit that modreq, then the generated proxy method signature won't match your interface's method signature, thus the error.

One solution might be to have DynamicProxy support a new framework target, e.g. .NET Standard 2.0, which quite possibly supports emitting custom modifiers (but I haven't checked at this point).

**Comment by TAGC** [comment]
I've found that Castle.Core fails to create a proxy for interfaces like this:

```cs
public interface IGenericStructByRefConsumer<T>
{
    T Consume(in Struct message);
}
```

These tests fail under both .NET Framework 4.6.1 and .NET Core 2.0:

```cs
[Fact]
internal void Struct_ByRef_Generic_Moq_Test()
{
    _ = Mock.Of<IGenericStructByRefConsumer<int>>();
}

[Fact]
internal void Struct_ByRef_Generic_NSubstitute_Test()
{
    _ = Substitute.For<IGenericStructByRefConsumer<int>>();
}
```

In the case of .NET Core, I get a similar sort of error to the other tests:

```
Signature of the body and declaration in a method implementation do not match.  Type: 'Castle.Proxies.IGenericStructByRefConsumer`1Proxy'.  Assembly: 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Under .NET Framework, I get a stacktrace like this:

```
Castle.DynamicProxy.ProxyGenerationException : There was an error in static constructor on type Castle.Proxies.IGenericStructByRefConsumer`1Proxy. This is likely a bug in DynamicProxy. Please report it.
---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
-------- System.TypeInitializationException : The type initializer for 'Castle.Proxies.IGenericStructByRefConsumer`1Proxy' threw an exception.
------------ System.MissingMethodException : Method not found: '!0 SomeProject.Tests.IGenericStructByRefConsumer`1.Consume(SomeProject.Tests.Struct ByRef)'.
   at Castle.DynamicProxy.Internal.TypeUtil.SetStaticField(Type type, String fieldName, BindingFlags additionalFlags, Object value)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.InitializeStaticFields(Type builtType)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithoutTargetGenerator.GenerateType(String typeName, Type proxyTargetType, Type[] interfaces, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.<>c__DisplayClass6_0.<GenerateCode>b__0(String n, INamingScope s)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCode(Type proxyTargetType, Type[] interfaces, ProxyGenerationOptions options)
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyTypeWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, IInterceptor[] interceptors)
```

**Comment by stakx** [comment]
@TAGC: .NET 4.6.1 probably prefers the .NET Standard 1.3 build to the .NET Framework builds (a problem that has cropped up since .NET 4.6.1 was retroactively changed to support .NET standard 2.0), explaining why it is affected by this as well.

**Comment by TAGC** [comment]
How hard would it be to fix this? I'd need to manually mock all my interfaces that use `in <valuetype>` methods otherwise, and I guess now that C# 7.2 is out a bunch of other people will be running into similar problems.

**Comment by jonorossi** [comment]
@TAGC I've renamed the issue title, no mocking happens here that is a mocking library concern. Thanks for the issue report, I'd usually start by asking for a test case against this library not another layer up your stack, but in this case it'll be easy to make that step.

Thanks @stakx, yes it definitely sounds like this is caused by custom modifiers not emitted when using the .NET Standard 1.3 build, I disliked writing that code during the DNX port.

It looks like `ParameterInfo.GetRequiredCustomModifiers` (and friends) are available in [.NET Standard 2.0, 1.6 and 1.5](https://docs.microsoft.com/en-au/dotnet/api/system.reflection.parameterinfo.getrequiredcustommodifiers?view=netstandard-2.0#System_Reflection_ParameterInfo_GetRequiredCustomModifiers), and the [coreclr has code for it](https://github.com/dotnet/coreclr/blob/57ee22e6086af5dfc06651dc002e24a71c3999ee/src/mscorlib/src/System/Reflection/RuntimeParameterInfo.cs#L495-L503).

I guess its time to also add a .NET Standard 2.0 build. However I don't think that will fix Moq (.NET Standard 1.3), NSubstitute (.NET Standard 1.3) or FakeItEasy (.NET Standard 1.6) without each project also releasing a .NET Standard 2.0 build which they do not do today, as NuGet will continue to use the .NET Standard 1.3 build. I don't think we really have any other options.

/cc @dtchepak @blairconrad @thomaslevesque

**Comment by stakx** [comment]
@jonorossi: I'll take care of support in Moq once an updated Castle.Core package is available. (I think I'll skip over .NET Standard 1.5 and 1.6 as framework targets and go straight to .NET Standard 2.0.)

**Comment by thomaslevesque** [comment]
> I guess its time to also add a .NET Standard 2.0 build

Why 2.0? If the necessary APIs are supported in 1.5, why not target the lowest possible version to support the largest number of consumers? Is there a compelling reason to target 2.0?

We [considered](https://github.com/FakeItEasy/FakeItEasy/issues/1186) releasing a netstandard2.0 version of FakeItEasy in order to support binary serialization (which is disabled in netstandard1.3 builds), but 

> .NET 4.6.1 probably prefers the .NET Standard 1.3 build to the .NET Framework builds (a problem that has cropped up since .NET 4.6.1 was retroactively changed to support .NET standard 2.0), explaining why it is affected by this as well.

I don't think that's the reason; I just tried it, making sure to reference the net45 version of Castle.Core, and the problem with the generic interface still occurs. I think this is a related but different bug.

**Comment by zvirja** [comment]
> guess its time to also add a .NET Standard 2.0 build

The same question from the NSubstitute side. If you can fix the issue in .NET Standard 1.5, it worth it to do that. The `Castle.Core` is the fundamental library and other libraries are based on it. If you don't select the minimal required version, you force all the downstream dependencies to be also unavailable for the earlier versions of .NET.

Probably that isn't so critical for the testing libraries like Moq or NSubstitute, however there might be other dependencies which offer the production functionality and it might hurt them.

**Comment by jonorossi** [comment]
> Why 2.0? If the necessary APIs are supported in 1.5, why not target the lowest possible version to support the largest number of consumers? Is there a compelling reason to target 2.0?

Thanks @thomaslevesque and @zvirja for the feedback, exactly why I CCed. I've just been seeing a lot of other libraries skip over or drop .NET Standard 1.x, I thought it was just the done thing now with .NET Standard 2.0 out (but obviously not). Also on the 2.0 side gives us full access to the .NET Standard 2.0 APIs, but I guess we aren't ready to let go of .NET Standard 1.x yet so there isn't much point. No problem, .NET Standard 1.5 it will be and we'll drop .NET Standard 1.3 in the next major version (that change only drops .NET Framework 4.6 in favour of 4.6.1).

> I don't think that's the reason; I just tried it, making sure to reference the net45 version of Castle.Core, and the problem with the generic interface still occurs. I think this is a related but different bug.

Thanks for the heads up, there might be a defect relating just to generics.

We need to get a full set of unit tests added for these cases. If someone wants to contribute them please do, just let everyone know, I won't have time to look at it tonight.

**Comment by thomaslevesque** [comment]
> .NET Standard 1.5 it will be and we'll drop .NET Standard 1.3 in the next major version (that change only drops .NET Framework 4.6 in favour of 4.6.1).

👍 
But if it's not too much trouble, it might be a good idea to keep 1.3 around (even if it doesn't support `in` parameters) in addition to 1.5, because Moq and NSubstitute still target it (not an issue for FakeItEasy, since we target 1.6)

**Comment by TAGC** [comment]
@thomaslevesque Both the Moq and NSubstitute guys have commented above that they're prepared to upgrade to .NET Standard 1.5+ when Castle.Core vNext gets released, so I guess it's not necessary to keep 1.3 around for their sake (although it might be for other, non-mocking related libraries).

**Comment by TAGC** [comment]
Hi, any update on how this is progressing?

**Comment by jonorossi** [comment]
> Hi, any update on how this is progressing?

@TAGC I'm not aware of anyone working on a pull request to add a .NET Standard 1.5 build defining `FEATURE_EMIT_CUSTOMMODIFIERS`, and/or investigating if there is an additional defect you were talking about in https://github.com/castleproject/Core/issues/339#issuecomment-372605885.

**Comment by stakx** [comment]
I had some free time today, so I took a stab at this and submitted a PR for this issue. I'm however not quite sure how to resolve the issues that popped up with the Travis CI build.

**Comment by stakx** [comment]
@jonorossi, @TAGC - regarding this second issue:

> I've found that Castle.Core fails to create a proxy for interfaces like this:
>
> ```csharp
> public interface IGenericStructByRefConsumer<T>
> {
>    T Consume(in Struct message);
> }
> ```
>
> [...]

I suspect that this might actually be due to a bug in System.Reflection.Emit, which DynamicProxy depends on. I've been able to boil it down to the following standalone test code (.NET Core 2.0, requires xUnit):

```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;
using Xunit;

public class Fixture
{
    // We'll need a `ModuleBuilder` to hold generated code.
    static Lazy<ModuleBuilder> moduleBuilder = new Lazy<ModuleBuilder>(() =>
        AssemblyBuilder
        .DefineDynamicAssembly(new AssemblyName("DynamicAssembly"), AssemblyBuilderAccess.Run)
        .DefineDynamicModule("DynamicModule"));

    // The following method returns a dynamically generated method roughly equivalent to `Get` in:
    //
    // class <RandomTypeName>
    // {
    //     public static Get()
    //         => MethodBase.GetMethodFromHandle(<method>.MethodHandle, <method>.DeclaringType.TypeHandle);
    // }
    static Func<MethodBase> DefineMethodThatReturns(MethodInfo method)
    {
        var getMethodFromHandle = typeof(MethodBase).GetMethod("GetMethodFromHandle", new[] { typeof(RuntimeMethodHandle), typeof(RuntimeTypeHandle) });

        var randomTypeName = "_" + Guid.NewGuid().ToString("N");
        var typeBuilder = moduleBuilder.Value.DefineType(randomTypeName, TypeAttributes.Class);

        var getMethodBuilder = typeBuilder.DefineMethod("Get", MethodAttributes.Public | MethodAttributes.Static, typeof(MethodBase), new Type[0]);
        var getMethodIL = getMethodBuilder.GetILGenerator();
        getMethodIL.Emit(OpCodes.Ldtoken, method);  // Reflection.Emit wants a MethodInfo, not a RuntimeMethodHandle
        getMethodIL.Emit(OpCodes.Ldtoken, method.DeclaringType);  // same for TypeInfo, instead of RuntimeTypeHandle
        getMethodIL.EmitCall(OpCodes.Call, getMethodFromHandle, null);
        getMethodIL.Emit(OpCodes.Ret);

        var type = typeBuilder.CreateType();
        return (Func<MethodBase>)type.GetMethod("Get").CreateDelegate(typeof(Func<MethodBase>));
    }

    // We're going to put the methods of each of these types into the above generator method:
    public interface WithoutIn    { void Method(   int arg); }
    public interface WithoutIn<T> { void Method(   int arg); }
    public interface WithIn       { void Method(in int arg); }
    public interface WithIn<T>    { void Method(in int arg); }

    public static object[][] Methods => new object[][]
    {
        new [] { typeof(WithoutIn)      },
        new [] { typeof(WithoutIn<int>) },
        new [] { typeof(WithIn)         },
        new [] { typeof(WithIn<int>)    },
    };

    [Theory]
    [MemberData(nameof(Methods))]
    public void GeneratedCodeWorksFor(Type type)
    {
        var method = type.GetMethod("Method");
        var getMethod = DefineMethodThatReturns(method);
        Assert.Same(method, getMethod());
    }
}
```

The dynamically generated method in this code is very similar to the type intializers (aka static constructors) that DynamicProxy produces in its dynamically generated proxy types.

Unless any of you can spot an obvious error in my test code, I'll submit a bug report over at dotnet/corefx.

**Comment by stakx** [comment]
> and/or investigating if there is an additional defect you were talking about in https://github.com/castleproject/Core/issues/339#issuecomment-372605885

It's likely a problem in the framework, not in DynamicProxy. See the dotnet/corefx issue linked to above.

**Comment by jonorossi** [comment]
Many thanks @stakx, great work!

I've responded on your pull request to get things going on .NET Core, I guess we'll wait to hopefully get a response from someone more versed in the CLR implementation as the work week starts.

**Comment by TAGC** [comment]
Thanks @stakx, I appreciate it!

**Comment by jonorossi** [comment]
I've merged #344 which gets things going, and is enough to ship.

I think it would be a great idea to add a failing unit test (marked ignored referencing the corefx issue) for the defect reported in https://github.com/dotnet/corefx/issues/29254 before we close out this defect.

**Comment by zvirja** [comment]
I feel that I started to be a bit confused, as previously you said that issue is at .NET Runtime side 😕 Given that you merged the PR and tests passed, does that mean that no issue is present there?

If issue is still present at .NET Runtime side, could you clarify which scenarios work and which ones are affected?

Thanks. Excuse me if I'm missing something obvious.

**Comment by jonorossi** [comment]
> I feel that I started to be a bit confused, as previously you said that issue is at .NET Runtime side 😕 Given that you merged the PR and tests passed, does that mean that no issue is present there?
> 
> If issue is still present at .NET Runtime side, could you clarify which scenarios work and which ones are affected?

@zvirja this issue isn't yet closed which is why my last comment is requesting we add ignored failing unit tests for the .NET runtime defect so it is clear what we expect not to work. `in` parameters didn't work at all on .NET Core because the .NET Standard 1.3 API doesn't expose the required reflection methods for us to emit custom modifiers, which is why we've added a .NET Standard 1.5 target which does expose these reflection methods, those methods have always been used on the .NET Framework.

You'll see @TAGC's https://github.com/castleproject/Core/issues/339#issuecomment-372605885 and https://github.com/dotnet/corefx/issues/29254 both have interfaces with a generic argument, the remaining defect is with generic types, however there might be other scenarios which we haven't yet discovered.

**Comment by stakx** [comment]
@jonorossi, I'll submit a PR with the skipped failing unit test.

**Comment by zvirja** [comment]
@jonorossi Thanks for the explanation. Do you have also any ETA this fix is released in a new version of the `Castle.Core` library?

**Comment by jonorossi** [comment]
@zvirja I just created #354 for the next release.
